Repository mateusfg7/trabalho-dev-web-periodo-ll, pull requests merged in 2024-10, with the labels that each got.

#13 Adiciona informações do projeto no `README.md`
  README.md
Labels: docs

#20 Atualiza a pagina de informações importantes
  advices.html
Labels: feature, HTML, CSS

#23 Adicionado o media query das páginas de contato e de agradecimento
  agradecimentos.html
  contato.html
Labels: feature, CSS

#19 pagina places
  IMAGE 1.1.png
  IMAGE 1.2.png
  IMAGE 1.3.png
  IMAGE 1.4.png
  IMAGE 1.5.png
  IMAGE 1.6.png
  MAIN_LOGO.png
  cssdoc.txt
  htmldoc.txt
  imgs/IMAGE 1.1.png
  imgs/IMAGE 1.2.png
  imgs/IMAGE 1.3.png
  imgs/IMAGE 1.4.png
  imgs/IMAGE 1.5.png
  imgs/IMAGE 1.6.png
  imgs/IMAGE 2.1.png
  imgs/IMAGE 2.2.png
  imgs/IMAGE 2.3.png
  imgs/IMAGE 2.4.png
  imgs/MAIN_LOGO.png
  mainpage.html
  new.css
  newdetails.html
  places.html
  styles.css
Labels: feature
